name: purchase_order
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.5.1
  excel: ^4.0.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 
