name: purchase_order
description: "A modern Purchase Order Management System built with Flutter, Firebase, and Clean Architecture."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.5.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  excel: ^4.0.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  gap: ^3.0.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  shared_preferences: ^2.3.3
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 
